#!/bin/bash

curl -s https://www.amfiindia.com/spages/NAVAll.txt -o NAVAll.txt

awk -F';' '
BEGIN { OFS="\t"; print "Scheme Name", "Asset Value" }
!/^#/ && NF > 4 { print $4, $5 }
' NAVAll.txt > nav_data.tsv

echo "Extraction complete. Saved to nav_data.tsv"
